### PR TITLE
Missing gulp-debug dependency

### PR DESCRIPTION
**Pull request by owndann**
I'm working with sass too and i love what yo did with this improve

### CODE REVIEW

**Comment by lifaon74** [comment]
Thanks to you

**Comment by owndann** [comment]
Are you still working on this? i found a issue when you put a bad url in a import it stops compiling and theres no warning or something maybe i can help.

**Comment by lifaon74** [comment]
Hum I didn't touch any import, and for me everything compile. Create an issue if needed.

But take in account that this repo is temporary and will (probably soon) be merge with the original one.

**Comment by owndann** [comment]
Ok but i'm having an issue with the serve.prod the scss is not there :(

**Comment by lifaon74** [comment]
if you build.prod, the scss becomes css and is minimified. Take a look at client/. I put a full demo on how to use scss

**Pull request merged**
